mock_mode: false
log_level: INFO
recipe_config_path: "recipe_config.yaml"

rabbitmq:
  host: "127.0.0.1"
  port: 5672
  username: "young"
  password: "young"
  virtual_host: "/"
  request_exchange: ""
  request_routing_key: "task.request"
  request_queue: "IPDK_WORKER_INTERFACE" #목표 큐 이름
  result_queue_base: "IPDK_WORKER_INTERFACE_RESULT" #받아올 큐 이름, 요청 보낼때 보내면 해당 큐이름으로 받아옴 
  request_queue_declare:
    durable: true
    exclusive: false
    auto_delete: false
    arguments:
      x-max-priority: 5
      module_group: "IPDK_WORKER"
  result_queue_declare:
    durable: true
    exclusive: false
    auto_delete: false
    arguments:
      x-max-priority: 5
      module_group: "default"
  heartbeat: 30
  blocked_connection_timeout: 30
  connection_attempts: 3
  retry_delay_seconds: 2.0
publish:
  default_action: "RUN_EXECUTE"
  default_priority: 0
  polling_interval_seconds: 5
  timeout_seconds: 86400
  max_messages_per_poll: 100
  max_publish_retries: 3
  publish_retry_backoff_seconds: 1.5
  initial_open_folders: 2
  max_active_open_folders: 3
  image_extensions: [".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff"]
  scan_mode: "direct"

ui:
  app_name: "RabbitMQ Task Tracker"
  window_width: 1480
  window_height: 900
  theme: "dark"
  font_family: "Segoe UI"
